package applications

import (
	"fmt"

	"github.com/futrx-com/remote.futrx.com/pkg/applications"
)

// backendModuleFile is the go.mod compiled for an application's backend. Its module
// path is local and never published; what matters is that the SDK keeps its
// canonical import path through the replace, so the same source compiles in a
// checkout of this repository and in this generated directory.
func (b *Builder) backendModuleFile() string {
	return fmt.Sprintf(`// Generated by the remote.futrx backend host. Do not edit.
module futrx.local/applications/application

go %s

require (
	%s v0.0.0
	%s %s
)

require (
%s)

replace %s => ../sdk
`,
		b.pins.goVersion,
		applications.ModulePath,
		goPluginModule, b.pins.require(goPluginModule, goPluginFallbackVersion),
		b.pins.indirectBlock(applications.ModulePath, goPluginModule),
		applications.ModulePath,
	)
}

// sdkModuleFile is the go.mod of the materialized SDK. It carries the same
// pins so the two modules agree without a workspace file.
func (b *Builder) sdkModuleFile() string {
	return fmt.Sprintf(`// Generated by the remote.futrx backend host. Do not edit.
module %s

go %s

require %s %s

require (
%s)
`,
		applications.ModulePath,
		b.pins.goVersion,
		goPluginModule, b.pins.require(goPluginModule, goPluginFallbackVersion),
		b.pins.indirectBlock(applications.ModulePath, goPluginModule),
	)
}

const (
	goPluginModule = "github.com/hashicorp/go-plugin"
	// goPluginFallbackVersion is used only when build info is unavailable,
	// which in practice means a test binary. TestGoPluginFallbackMatchesGoMod
	// keeps it in step with the server's own requirement.
	goPluginFallbackVersion = "v1.8.0"
)
